version: "3.4"
services:
  sshd:
    hostname: docker-container
    networks:
      - "net"
    image: sshd:latest
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    ports:
      - "22:22"

networks:
  net:
    driver: overlay
    ipam:
      driver: default
      config:
        - subnet: 192.168.100.0/24
